apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
          args:
            - --http-address=0.0.0.0:4180
          env:
            - name: OAUTH2_PROXY_PROVIDER
              value: "oidc"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: "oauth2-proxy"
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: OAUTH2_PROXY_CLIENT_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-proxy-secret
                  key: OAUTH2_PROXY_COOKIE_SECRET
            - name: OAUTH2_PROXY_COOKIE_SECURE
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_WHITELIST_DOMAIN
              value: ".uw.local"
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://uw.local/oauth2/callback"
            - name: OAUTH2_PROXY_UPSTREAMS
              value: "http://web-ui:4200/"
            - name: OAUTH2_PROXY_LISTEN_ADDRESS
              value: "0.0.0.0:4180"
            - name: OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION
              value: "true"
            - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
              value: "true"
            - name: OAUTH2_PROXY_SKIP_OIDC_DISCOVERY
              value: "true"
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: "https://keycloak:8080/auth/realms/uwatcher"
            - name: OAUTH2_PROXY_LOGIN_URL
              value: "https://uw.local/auth/realms/uwatcher/protocol/openid-connect/auth"
            - name: OAUTH2_PROXY_REDEEM_URL
              value: "http://keycloak:8080/auth/realms/uwatcher/protocol/openid-connect/token"
            - name: OAUTH2_PROXY_PROFILE_URL
              value: "http://keycloak:8080/auth/realms/uwatcher/protocol/openid-connect/userinfo"
            - name: OAUTH2_PROXY_OIDC_JWKS_URL
              value: "http://keycloak:8080/auth/realms/uwatcher/protocol/openid-connect/certs"
          ports:
            - containerPort: 4180
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
