apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_SECRET: oP50OnQsgA82NOemthEHNKxgs4oL1OkQ
  OAUTH2_PROXY_COOKIE_SECRET: 6nWci6Vb8K6WyiL9HQUfryY0wpIDcogjtOsswvM8K3E=
