apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      name: "ng80"
    - protocol: TCP
      port: 443
      name: "ng443"
